---
title: "Cordell Browne"
output:
  html_document:
      css: index.css
      highlight: pygments
      theme: cosmo
      toc: yes
      toc_float: yes
---

<br>

# About Me 

I Am fueled by my passion for learning; I consider myself a ‘forever student,’ eager to both build on  academic foundations in biology and medicine and stay in tune with the latest digital research through continued coursework and professional development. Medicine  and data analytics related to it draw me in because it lies at the intersection of human connection, scientific inquiry, and social change. As a researcher I want to support the studies that could be beneficial to the population's health and wealth, and I hope to have a broader impact on healthcare through a combination of bioinformatics and clinical research.

My clinical and analytical experiences comes from extensive volunteer research at Shepherd's Hope Clinic in Orlando. I also took on positions like eligibility specialist, to assess whether or not patients qualified for coverage, front desk and discharge, medical scribe, took vitals, and perform overall performed a wide range of task for the clinic. 





